### ISSUE TITLE
Caching Feature

### ISSUE THREAD

**Issue by firwer** [UPetit/python-binance-profit#17]
Hello there! I tried the market order function and it works very well. I just got one feedback for the program.

Would it be possible to introduce a caching system into the program such that the order/trading speed can be improved on? In short, the communication and execution time taken between the program and binance api can shortened for rapid order execution.

Cheers!

**Comment by PhilippeGalvan** [comment]
Hello @firwer,

Thanks for the feedback.

In the current way buy/sell cycle is made, I don't think any caching could improve the order/trading speed.
From my current understanding every call made to binance api is a "refresh" or "action" call which shouldn't be cached in order to work as excepted, there are 2 bottlenecks: Binance API and buy order completion time.

@UPetit will correct me if I'm wrong but here is the actual buy/sell order life cycle in the script. 
No call is trully idempotent even the getStatus which we actually check for a change of state.

![buy sell cycle](https://user-images.githubusercontent.com/49376995/107505765-77454d00-6b9d-11eb-8bb4-26afae1486c9.png)

However, if you consider that a value won't be updated in a reasonable amount of time (like symbol informations), this value could be cached (or persisted locally) if the cost of operation and implementation vs efficiency gain is worth it.

**Comment by UPetit** [comment]
@PhilippeGalvan You're right! I will double check Binance API if they are mentioning a caching feature somewhere.

@firwer Did you use a script that is using a caching system? If yes, could you please share the link or the documentation? Thank you

**Comment by UPetit** [comment]
I'm closing this issue as it doesn't seem to be possible here. Happy to re-open it if needed.
